/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type {
  BamlRuntime,
  BamlCtxManager,
  ClientRegistry,
  Image,
  Audio,
  Pdf,
  Video,
  Collector,
} from "@boundaryml/baml";
import { toBamlError } from "@boundaryml/baml";
import type { Checked, Check } from "./types";
import type { partial_types } from "./partial_types";
import type * as types from "./types";
import type {
  CandidateSkills,
  ClassifiedSkill,
  Currency,
  EmploymentType,
  EngagementType,
  EnglishLevel,
  ExtractedCandidate,
  ExtractedLocation,
  ExtractedVacancy,
  ResumeContactInfo,
  ResumeEducationItem,
  ResumeExperienceItem,
  ResumeProjectItem,
  ResumeSkillGroup,
  Salary,
  Seniority,
  SkillCategory,
  SkillToClassify,
  Skills,
  StructuredResumeExtract,
  TailoredBullet,
  WorkFormat,
} from "./types";
import type TypeBuilder from "./type_builder";

export class LlmResponseParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ClassifySkills(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.ClassifiedSkill[] {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ClassifySkills",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ClassifiedSkill[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractCandidate(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.ExtractedCandidate {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractCandidate",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ExtractedCandidate;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractResume(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.StructuredResumeExtract {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractResume",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.StructuredResumeExtract;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractVacancy(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.ExtractedVacancy {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractVacancy",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.ExtractedVacancy;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorBullet(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): types.TailoredBullet {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "TailorBullet",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as types.TailoredBullet;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class LlmStreamParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ClassifySkills(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.ClassifiedSkill[] {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ClassifySkills",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ClassifiedSkill[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractCandidate(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.ExtractedCandidate {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractCandidate",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ExtractedCandidate;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractResume(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.StructuredResumeExtract {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractResume",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.StructuredResumeExtract;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractVacancy(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.ExtractedVacancy {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "ExtractVacancy",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.ExtractedVacancy;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorBullet(
    llmResponse: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      env?: Record<string, string | undefined>;
    },
  ): partial_types.TailoredBullet {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );
      return this.runtime.parseLlmResponse(
        "TailorBullet",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        __env__,
      ) as partial_types.TailoredBullet;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
