/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Currency,  EmploymentType,  EngagementType,  EnglishLevel,  ExtractedLocation,  ExtractedVacancy,  Salary,  Seniority,  Skills,  WorkFormat } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface ExtractedLocation {
      city?: string | null
      country?: string | null
    }
    export interface ExtractedVacancy {
      role?: string | null
      seniority?: types.Seniority | null
      skills?: Skills | null
      experienceYears?: number | null
      salary?: Salary | null
      englishLevel?: types.EnglishLevel | null
      employmentType?: types.EmploymentType | null
      workFormat?: types.WorkFormat | null
      locations: ExtractedLocation[]
      domain?: string | null
      engagementType?: types.EngagementType | null
      companyName?: string | null
      hasTestAssignment?: boolean | null
      hasReservation?: boolean | null
    }
    export interface Salary {
      min?: number | null
      max?: number | null
      currency?: types.Currency | null
    }
    export interface Skills {
      required: string[]
      optional: string[]
    }
}