/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";
import type { Checked, Check } from "./types";
import type {
  CandidateSkills,
  ClassifiedSkill,
  CoverLetter,
  Currency,
  EmploymentType,
  EngagementType,
  EnglishLevel,
  ExtractedCandidate,
  ExtractedLocation,
  ExtractedVacancy,
  InterviewQuestion,
  ResumeContactInfo,
  ResumeEducationItem,
  ResumeExperienceItem,
  ResumeProjectItem,
  ResumeSkillGroup,
  Salary,
  Seniority,
  SkillCategory,
  SkillToClassify,
  Skills,
  StructuredResumeExtract,
  TailorInputBullet,
  TailorOutputBullet,
  TailoredBullet,
  WorkFormat,
} from "./types";
import type * as types from "./types";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
  value: T;
  state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
  export interface CandidateSkills {
    required: string[];
    optional: string[];
  }
  export interface ClassifiedSkill {
    nodeId?: string | null;
    category?: types.SkillCategory | null;
    stack?: string | null;
    isCore?: boolean | null;
    generic?: boolean | null;
  }
  export interface CoverLetter {
    text?: string | null;
  }
  export interface ExtractedCandidate {
    role?: string | null;
    seniority?: types.Seniority | null;
    skills?: CandidateSkills | null;
    experienceYears?: number | null;
    englishLevel?: types.EnglishLevel | null;
  }
  export interface ExtractedLocation {
    city?: string | null;
    country?: string | null;
  }
  export interface ExtractedVacancy {
    role?: string | null;
    isTech?: boolean | null;
    seniority?: types.Seniority | null;
    skills?: Skills | null;
    experienceYears?: number | null;
    salary?: Salary | null;
    englishLevel?: types.EnglishLevel | null;
    employmentType?: types.EmploymentType | null;
    workFormat?: types.WorkFormat | null;
    locations: ExtractedLocation[];
    domain?: string | null;
    engagementType?: types.EngagementType | null;
    companyName?: string | null;
    hasTestAssignment?: boolean | null;
    hasReservation?: boolean | null;
  }
  export interface InterviewQuestion {
    question?: string | null;
    angle?: string | null;
    evidence?: string | null;
  }
  export interface ResumeContactInfo {
    location?: string | null;
    email?: string | null;
    phone?: string | null;
    linkedin?: string | null;
    github?: string | null;
    telegram?: string | null;
  }
  export interface ResumeEducationItem {
    degree?: string | null;
    school?: string | null;
    dates?: string | null;
  }
  export interface ResumeExperienceItem {
    role?: string | null;
    org?: string | null;
    dates?: string | null;
    context?: string | null;
    bullets: string[];
  }
  export interface ResumeProjectItem {
    name?: string | null;
    meta?: string | null;
    link?: string | null;
    context?: string | null;
    bullets: string[];
  }
  export interface ResumeSkillGroup {
    group?: string | null;
    items: string[];
  }
  export interface Salary {
    min?: number | null;
    max?: number | null;
    currency?: types.Currency | null;
  }
  export interface SkillToClassify {
    nodeId?: string | null;
    name?: string | null;
  }
  export interface Skills {
    required: string[];
    optional: string[];
  }
  export interface StructuredResumeExtract {
    name?: string | null;
    title?: string | null;
    contacts?: ResumeContactInfo | null;
    summary?: string | null;
    skills: ResumeSkillGroup[];
    experience: ResumeExperienceItem[];
    projects: ResumeProjectItem[];
    education: ResumeEducationItem[];
  }
  export interface TailorInputBullet {
    id?: string | null;
    text?: string | null;
  }
  export interface TailorOutputBullet {
    id?: string | null;
    text?: string | null;
  }
  export interface TailoredBullet {
    text?: string | null;
  }
}
