/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video } from "@boundaryml/baml";
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml";
import type { Checked, Check } from "./types";
import type * as types from "./types";
import type {
  CandidateSkills,
  ClassifiedSkill,
  CoverLetter,
  Currency,
  EmploymentType,
  EngagementType,
  EnglishLevel,
  ExtractedCandidate,
  ExtractedLocation,
  ExtractedVacancy,
  InterviewQuestion,
  ResumeContactInfo,
  ResumeEducationItem,
  ResumeExperienceItem,
  ResumeProjectItem,
  ResumeSkillGroup,
  Salary,
  Seniority,
  SkillCategory,
  SkillToClassify,
  Skills,
  StructuredResumeExtract,
  TailorInputBullet,
  TailorOutputBullet,
  TailoredBullet,
  WorkFormat,
} from "./types";
import type TypeBuilder from "./type_builder";
import type * as events from "./events";

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
  client?: string;
  env?: Record<string, string | undefined>;
  events?: EventsT;
};

export class HttpRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ClassifySkills(
    skills: types.SkillToClassify[],
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ClassifySkills",
        {
          skills: skills,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  DraftCoverLetter(
    candidateName: string,
    role: string,
    company: string,
    achievements: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DraftCoverLetter",
        {
          candidateName: candidateName,
          role: role,
          company: company,
          achievements: achievements,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractCandidate(
    text: string,
    knownRoles: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractCandidate",
        {
          text: text,
          knownRoles: knownRoles,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractResume(text: string, __baml_options__?: BamlCallOptions<never>): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractResume",
        {
          text: text,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractVacancy(
    text: string,
    knownRoles: string,
    knownDomains: string,
    knownSkills: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractVacancy",
        {
          text: text,
          knownRoles: knownRoles,
          knownDomains: knownDomains,
          knownSkills: knownSkills,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  InterviewPrep(
    role: string,
    strengths: string,
    gaps: string,
    achievements: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "InterviewPrep",
        {
          role: role,
          strengths: strengths,
          gaps: gaps,
          achievements: achievements,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorBullet(
    source: string,
    allowedTech: string,
    emphasis: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "TailorBullet",
        {
          source: source,
          allowedTech: allowedTech,
          emphasis: emphasis,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorResume(
    bullets: types.TailorInputBullet[],
    role: string,
    emphasis: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "TailorResume",
        {
          bullets: bullets,
          role: role,
          emphasis: emphasis,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class HttpStreamRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ClassifySkills(
    skills: types.SkillToClassify[],
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ClassifySkills",
        {
          skills: skills,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  DraftCoverLetter(
    candidateName: string,
    role: string,
    company: string,
    achievements: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DraftCoverLetter",
        {
          candidateName: candidateName,
          role: role,
          company: company,
          achievements: achievements,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractCandidate(
    text: string,
    knownRoles: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractCandidate",
        {
          text: text,
          knownRoles: knownRoles,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractResume(text: string, __baml_options__?: BamlCallOptions<never>): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractResume",
        {
          text: text,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractVacancy(
    text: string,
    knownRoles: string,
    knownDomains: string,
    knownSkills: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ExtractVacancy",
        {
          text: text,
          knownRoles: knownRoles,
          knownDomains: knownDomains,
          knownSkills: knownSkills,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  InterviewPrep(
    role: string,
    strengths: string,
    gaps: string,
    achievements: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "InterviewPrep",
        {
          role: role,
          strengths: strengths,
          gaps: gaps,
          achievements: achievements,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorBullet(
    source: string,
    allowedTech: string,
    emphasis: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "TailorBullet",
        {
          source: source,
          allowedTech: allowedTech,
          emphasis: emphasis,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  TailorResume(
    bullets: types.TailorInputBullet[],
    role: string,
    emphasis: string,
    __baml_options__?: BamlCallOptions<never>,
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [
          string,
          string,
        ][],
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "TailorResume",
        {
          bullets: bullets,
          role: role,
          emphasis: emphasis,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
