/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Currency {
  USD = "USD",
  EUR = "EUR",
  UAH = "UAH",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  CONTRACT = "CONTRACT",
  FREELANCE = "FREELANCE",
  INTERNSHIP = "INTERNSHIP",
}

export enum EngagementType {
  PRODUCT = "PRODUCT",
  OUTSOURCE = "OUTSOURCE",
  OUTSTAFF = "OUTSTAFF",
  STARTUP = "STARTUP",
  AGENCY = "AGENCY",
}

export enum EnglishLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  UPPER_INTERMEDIATE = "UPPER_INTERMEDIATE",
  ADVANCED = "ADVANCED",
  NATIVE = "NATIVE",
}

export enum RequirementPriority {
  MUST = "MUST",
  NICE = "NICE",
}

export enum RequirementsV2Role {
  AI_ENGINEER = "AI_ENGINEER",
  ANDROID_ENGINEER = "ANDROID_ENGINEER",
  AUTOMATION_QA_ENGINEER = "AUTOMATION_QA_ENGINEER",
  BACKEND_ENGINEER = "BACKEND_ENGINEER",
  BLOCKCHAIN_ENGINEER = "BLOCKCHAIN_ENGINEER",
  BUSINESS_ANALYST = "BUSINESS_ANALYST",
  COMPUTER_VISION_ENGINEER = "COMPUTER_VISION_ENGINEER",
  CROSS_PLATFORM_MOBILE_ENGINEER = "CROSS_PLATFORM_MOBILE_ENGINEER",
  DATA_ANALYST = "DATA_ANALYST",
  DATA_ENGINEER = "DATA_ENGINEER",
  DATA_SCIENTIST = "DATA_SCIENTIST",
  DATABASE_ENGINEER = "DATABASE_ENGINEER",
  DEVOPS_ENGINEER = "DEVOPS_ENGINEER",
  EMBEDDED_ENGINEER = "EMBEDDED_ENGINEER",
  ENGINEERING_MANAGER = "ENGINEERING_MANAGER",
  ERP_CRM_ENGINEER = "ERP_CRM_ENGINEER",
  FPGA_ENGINEER = "FPGA_ENGINEER",
  FRONTEND_ENGINEER = "FRONTEND_ENGINEER",
  FULL_STACK_ENGINEER = "FULL_STACK_ENGINEER",
  GAME_ENGINEER = "GAME_ENGINEER",
  HARDWARE_ENGINEER = "HARDWARE_ENGINEER",
  IOS_ENGINEER = "IOS_ENGINEER",
  IT_SUPPORT_ENGINEER = "IT_SUPPORT_ENGINEER",
  MACHINE_LEARNING_ENGINEER = "MACHINE_LEARNING_ENGINEER",
  MANUAL_QA_ENGINEER = "MANUAL_QA_ENGINEER",
  NETWORK_ENGINEER = "NETWORK_ENGINEER",
  SECURITY_ENGINEER = "SECURITY_ENGINEER",
  SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER",
  SYSTEMS_ADMINISTRATOR = "SYSTEMS_ADMINISTRATOR",
  WEB_CMS_ENGINEER = "WEB_CMS_ENGINEER",
}

export enum Seniority {
  INTERN = "INTERN",
  JUNIOR = "JUNIOR",
  MIDDLE = "MIDDLE",
  SENIOR = "SENIOR",
  LEAD = "LEAD",
  PRINCIPAL = "PRINCIPAL",
  C_LEVEL = "C_LEVEL",
}

export enum SkillCategory {
  LANGUAGE = "LANGUAGE",
  FRAMEWORK = "FRAMEWORK",
  LIBRARY = "LIBRARY",
  DATASTORE = "DATASTORE",
  CLOUD = "CLOUD",
  TOOL = "TOOL",
  PRACTICE = "PRACTICE",
  SOFT = "SOFT",
}

export enum WorkFormat {
  REMOTE = "REMOTE",
  OFFICE = "OFFICE",
  HYBRID = "HYBRID",
}

export interface CandidateSkills {
  required: string[]
  optional: string[]
  
}

export interface ClassifiedSkill {
  nodeId: string
  category: SkillCategory
  stack?: string | null
  isCore: boolean
  generic: boolean
  
}

export interface ExtractedCandidate {
  role?: string | null
  seniority?: Seniority | null
  skills: CandidateSkills
  experienceYears?: number | null
  englishLevel?: EnglishLevel | null
  
}

export interface ExtractedLocation {
  city: string
  country: string
  
}

export interface ExtractedVacancy {
  role?: string | null
  isTech: boolean
  seniority?: Seniority | null
  skills: Skills
  experienceYears?: number | null
  salary?: Salary | null
  englishLevel?: EnglishLevel | null
  employmentType?: EmploymentType | null
  workFormat?: WorkFormat | null
  locations: ExtractedLocation[]
  domain?: string | null
  engagementType?: EngagementType | null
  companyName?: string | null
  hasTestAssignment?: boolean | null
  hasReservation?: boolean | null
  
}

export interface ExtractedVacancyRequirementsV2 {
  role?: RequirementsV2Role | null
  isTech: boolean
  seniority?: Seniority | null
  requirements: VacancyRequirementV2[]
  
}

export interface Salary {
  min?: number | null
  max?: number | null
  currency?: Currency | null
  
}

export interface SkillToClassify {
  nodeId: string
  name: string
  
}

export interface Skills {
  required: string[]
  optional: string[]
  
}

export interface VacancyRequirementV2 {
  priority: RequirementPriority
  value?: string | null
  anyOf?: string[] | null
  
}
