/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Currency {
  USD = "USD",
  EUR = "EUR",
  UAH = "UAH",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  CONTRACT = "CONTRACT",
  FREELANCE = "FREELANCE",
  INTERNSHIP = "INTERNSHIP",
}

export enum EngagementType {
  PRODUCT = "PRODUCT",
  OUTSOURCE = "OUTSOURCE",
  OUTSTAFF = "OUTSTAFF",
  STARTUP = "STARTUP",
  AGENCY = "AGENCY",
}

export enum EnglishLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  UPPER_INTERMEDIATE = "UPPER_INTERMEDIATE",
  ADVANCED = "ADVANCED",
  NATIVE = "NATIVE",
}

export enum Seniority {
  INTERN = "INTERN",
  JUNIOR = "JUNIOR",
  MIDDLE = "MIDDLE",
  SENIOR = "SENIOR",
  LEAD = "LEAD",
  PRINCIPAL = "PRINCIPAL",
  C_LEVEL = "C_LEVEL",
}

export enum WorkFormat {
  REMOTE = "REMOTE",
  OFFICE = "OFFICE",
  HYBRID = "HYBRID",
}

export interface ExtractedLocation {
  city: string
  country: string
  
}

export interface ExtractedVacancy {
  role?: string | null
  seniority?: Seniority | null
  skills: Skills
  experienceYears?: number | null
  salary?: Salary | null
  englishLevel?: EnglishLevel | null
  employmentType?: EmploymentType | null
  workFormat?: WorkFormat | null
  locations: ExtractedLocation[]
  domain?: string | null
  engagementType?: EngagementType | null
  companyName?: string | null
  hasTestAssignment: boolean
  hasReservation: boolean
  
}

export interface Salary {
  min?: number | null
  max?: number | null
  currency?: Currency | null
  
}

export interface Skills {
  required: string[]
  optional: string[]
  
}
