/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    CandidateSkills: ClassViewer<'CandidateSkills', "required" | "optional">;
    
    ClassifiedSkill: ClassViewer<'ClassifiedSkill', "nodeId" | "category" | "stack" | "isCore" | "generic">;
    
    ExtractedCandidate: ClassViewer<'ExtractedCandidate', "role" | "seniority" | "skills" | "experienceYears" | "englishLevel">;
    
    ExtractedLocation: ClassViewer<'ExtractedLocation', "city" | "country">;
    
    ExtractedVacancy: ClassViewer<'ExtractedVacancy', "role" | "isTech" | "seniority" | "skills" | "experienceYears" | "salary" | "englishLevel" | "employmentType" | "workFormat" | "locations" | "domain" | "engagementType" | "companyName" | "hasTestAssignment" | "hasReservation">;
    
    Salary: ClassViewer<'Salary', "min" | "max" | "currency">;
    
    SkillToClassify: ClassViewer<'SkillToClassify', "nodeId" | "name">;
    
    Skills: ClassViewer<'Skills', "required" | "optional">;
    
    
    Currency: EnumViewer<'Currency', "USD" | "EUR" | "UAH">;
    
    EmploymentType: EnumViewer<'EmploymentType', "FULL_TIME" | "PART_TIME" | "CONTRACT" | "FREELANCE" | "INTERNSHIP">;
    
    EngagementType: EnumViewer<'EngagementType', "PRODUCT" | "OUTSOURCE" | "OUTSTAFF" | "STARTUP" | "AGENCY">;
    
    EnglishLevel: EnumViewer<'EnglishLevel', "BEGINNER" | "INTERMEDIATE" | "UPPER_INTERMEDIATE" | "ADVANCED" | "NATIVE">;
    
    Seniority: EnumViewer<'Seniority', "INTERN" | "JUNIOR" | "MIDDLE" | "SENIOR" | "LEAD" | "PRINCIPAL" | "C_LEVEL">;
    
    SkillCategory: EnumViewer<'SkillCategory', "LANGUAGE" | "FRAMEWORK" | "LIBRARY" | "DATASTORE" | "CLOUD" | "TOOL" | "PRACTICE" | "SOFT">;
    
    WorkFormat: EnumViewer<'WorkFormat', "REMOTE" | "OFFICE" | "HYBRID">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "CandidateSkills","ClassifiedSkill","ExtractedCandidate","ExtractedLocation","ExtractedVacancy","Salary","SkillToClassify","Skills",
          ]),
          enums: new Set([
            "Currency","EmploymentType","EngagementType","EnglishLevel","Seniority","SkillCategory","WorkFormat",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.CandidateSkills = this.tb.classViewer("CandidateSkills", [
          "required","optional",
        ]);
        
        this.ClassifiedSkill = this.tb.classViewer("ClassifiedSkill", [
          "nodeId","category","stack","isCore","generic",
        ]);
        
        this.ExtractedCandidate = this.tb.classViewer("ExtractedCandidate", [
          "role","seniority","skills","experienceYears","englishLevel",
        ]);
        
        this.ExtractedLocation = this.tb.classViewer("ExtractedLocation", [
          "city","country",
        ]);
        
        this.ExtractedVacancy = this.tb.classViewer("ExtractedVacancy", [
          "role","isTech","seniority","skills","experienceYears","salary","englishLevel","employmentType","workFormat","locations","domain","engagementType","companyName","hasTestAssignment","hasReservation",
        ]);
        
        this.Salary = this.tb.classViewer("Salary", [
          "min","max","currency",
        ]);
        
        this.SkillToClassify = this.tb.classViewer("SkillToClassify", [
          "nodeId","name",
        ]);
        
        this.Skills = this.tb.classViewer("Skills", [
          "required","optional",
        ]);
        
        
        this.Currency = this.tb.enumViewer("Currency", [
          "USD","EUR","UAH",
        ]);
        
        this.EmploymentType = this.tb.enumViewer("EmploymentType", [
          "FULL_TIME","PART_TIME","CONTRACT","FREELANCE","INTERNSHIP",
        ]);
        
        this.EngagementType = this.tb.enumViewer("EngagementType", [
          "PRODUCT","OUTSOURCE","OUTSTAFF","STARTUP","AGENCY",
        ]);
        
        this.EnglishLevel = this.tb.enumViewer("EnglishLevel", [
          "BEGINNER","INTERMEDIATE","UPPER_INTERMEDIATE","ADVANCED","NATIVE",
        ]);
        
        this.Seniority = this.tb.enumViewer("Seniority", [
          "INTERN","JUNIOR","MIDDLE","SENIOR","LEAD","PRINCIPAL","C_LEVEL",
        ]);
        
        this.SkillCategory = this.tb.enumViewer("SkillCategory", [
          "LANGUAGE","FRAMEWORK","LIBRARY","DATASTORE","CLOUD","TOOL","PRACTICE","SOFT",
        ]);
        
        this.WorkFormat = this.tb.enumViewer("WorkFormat", [
          "REMOTE","OFFICE","HYBRID",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}