// GENERATED by scripts/check-baml-production-identity.mjs. Do not edit.
// Only production BAML files are included: test fixtures must not invalidate
// production cache entries.
export const BAML_PRODUCTION_SOURCE_HASH =
  "e372bd2053885abfb322c724edb84c30ef30c7a297e12741632339d354a8d853";
export const BAML_RUNTIME_VERSION = "0.222.0";
