// GENERATED by scripts/check-baml-production-identity.mjs. Do not edit.
// Only production BAML files are included: test fixtures must not invalidate
// production cache entries.
export const BAML_PRODUCTION_SOURCE_HASH =
  "cf8dbd734ef3839a3d792b6dd94ce71ccc7f025e92b04784564b933ab2e84af3";
export const BAML_RUNTIME_VERSION = "0.222.0";
